sudo: false

#PHP
language: php
php:
  - 5.5
  - 5.4

env:
  - WP_VERSION=4.3
  - WP_VERSION=4.2

before_install:
  # setup tools
  - npm install -g grunt-cli
  - gem install sass
  # - npm install
  # - composer install
  - sass style3.scss sassy.css
  - cat sassy.css

  # setup Wordpress installation
  - export WP_DEVELOP_DIR=/tmp/wordpress/
  - mkdir -p $WP_DEVELOP_DIR
  - git clone --depth=1 --branch="$WP_VERSION" git://develop.git.wordpress.org/ $WP_DEVELOP_DIR
  - plugin_slug=$(basename $(pwd))
  - plugin_dir=$WP_DEVELOP_DIR/src/wp-content/plugins/$plugin_slug
  - cd ..
  - mv $plugin_slug $plugin_dir

  - echo $WP_DEVELOP_DIR
  - cd $WP_DEVELOP_DIR
  - cp wp-tests-config-sample.php wp-tests-config.php
  - sed -i "s/youremptytestdbnamehere/wordpress_test/" wp-tests-config.php
  - sed -i "s/yourusernamehere/travis/" wp-tests-config.php
  - sed -i "s/yourpasswordhere//" wp-tests-config.php

  - mysql -e 'CREATE DATABASE wordpress_test;' -uroot
  - cd $plugin_dir

script: phpunit
